added basic support for self healing etcd cluster update krib-config to recover a master in existing cluster. Fixes /issues/239 added a method to parse latest release version from gitub api. Fixes /issues/240

diff --git a/krib/templates/krib-helm-init.sh.tmpl b/krib/templates/krib-helm-init.sh.tmpl
--- a/krib/templates/krib-helm-init.sh.tmpl
+++ b/krib/templates/krib-helm-init.sh.tmpl
@@ -34,13 +34,21 @@ if [[ $MASTER_INDEX != notme ]] ; then
     fi
 
     # todo: provide more options for installing helm
-    curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
+    {{ if eq (.Param "helm/version") "latest" -}}
+    # curl has exit code 23... meh
+    set +e
+    HELM_VERSION=$(curl -skX GET "https://api.github.com/repos/helm/helm/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')
+    set -e
+    {{ else -}}
+    HELM_VERSION={{.Param "helm/version"}}
+    {{ end -}}
+    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
     chmod 700 get_helm.sh
     INSTALL_DIR=/usr/local/bin
     if [[ $OS_FAMILY == coreos ]] ; then
       INSTALL_DIR=/opt/bin
     fi
-    HELM_INSTALL_DIR=$INSTALL_DIR ./get_helm.sh -v {{.Param "helm/version"}}
+    HELM_INSTALL_DIR=$INSTALL_DIR ./get_helm.sh -v ${HELM_VERSION}
 
     echo "Create tiller service account"
     kubectl apply -f tiller-rbac.yaml
