Parametize target disk

diff --git a/krib/tasks/krib-dev-reset.yaml b/krib/tasks/krib-dev-reset.yaml
--- a/krib/tasks/krib-dev-reset.yaml
+++ b/krib/tasks/krib-dev-reset.yaml
@@ -235,6 +235,7 @@ Templates:
     rm -rf /var/log/containers/* || echo "/var/log/containers doesn't exist, possibly we weren't using containerd"
     iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
 
+    {{ if .ParamExists "rook/ceph-target-disk"}}
     {{if .ParamExists "krib/selective-mastership" -}}
     SELECTIVE_MASTERSHIP={{.Param "krib/selective-mastership" }}
     {{end -}}
@@ -243,18 +244,36 @@ Templates:
     {{end -}}
     if [[ "$SELECTIVE_MASTERSHIP" == true ]] ; then
       if [[ ! "$I_AM_MASTER" == true ]] ; then
-        # I'm a worker, so wipe /dev/sda in preparation for ceph
+        # I'm a worker, so wipe disk in preparation for next ceph installation
         yum install -y gdisk
-        sgdisk --zap-all /dev/sda
-
+        sgdisk --zap-all /dev/{{ .Param "rook/ceph-target-disk" }}
         # Now remove devicemapper details
         for i in `ls /dev/mapper/ceph*`; do dmsetup remove $i || echo "Failed to remove but failing gracefully to continue script"; done
-
       fi
     fi
-
-    
+    {{ end -}}
   Name: KRIB wipe machine for cluster reinstall  
+- Contents: |-
+    #!/bin/bash
+
+    {{ if .ParamExists "rook/ceph-target-disk"}}
+    {{if .ParamExists "krib/selective-mastership" -}}
+    SELECTIVE_MASTERSHIP={{.Param "krib/selective-mastership" }}
+    {{end -}}
+    {{if .ParamExists "krib/i-am-master" -}}
+    I_AM_MASTER={{.Param "krib/i-am-master" }}
+    {{end -}}
+    if [[ "$SELECTIVE_MASTERSHIP" == true ]] ; then
+      if [[ ! "$I_AM_MASTER" == true ]] ; then
+        # I'm a worker, so wipe disk in preparation for next ceph installation
+        yum install -y gdisk
+        sgdisk --zap-all /dev/{{ .Param "rook/ceph-target-disk" }}
+        # Now remove devicemapper details
+        for i in `ls /dev/mapper/ceph*`; do dmsetup remove $i || echo "Failed to remove but failing gracefully to continue script"; done
+      fi
+    fi
+    {{ end -}}
+  Name: KRIB wipe disks used for rook-ceph (if configured)  
 Meta:
   icon: "ship"
   color: "orange"
