fix(edge-lab): SELinux and version for k3s, admin-user for dashboard

diff --git a/edge-lab/tasks/edge-lab-install-dashboard.yaml b/edge-lab/tasks/edge-lab-install-dashboard.yaml
--- a/edge-lab/tasks/edge-lab-install-dashboard.yaml
+++ b/edge-lab/tasks/edge-lab-install-dashboard.yaml
@@ -18,16 +18,16 @@ OptionalParams:
   - edge-lab/dashboard-token
 Templates:
   - Name: "dashboard-adminuser.yaml"
-    Path: ""
-    Contents: |
+    Path: "dashboard-adminuser.yaml"
+    Contents: |-
       apiVersion: v1
       kind: ServiceAccount
       metadata:
         name: admin-user
         namespace: kubernetes-dashboard
   - Name: "cluster-binding.yaml"
-    Path: ""
-    Contents: |
+    Path: "cluster-binding.yaml"
+    Contents: |-
       apiVersion: rbac.authorization.k8s.io/v1
       kind: ClusterRoleBinding
       metadata:
@@ -41,7 +41,6 @@ Templates:
         name: admin-user
         namespace: kubernetes-dashboard
   - Name: "dashboard.sh"
-    Path: ""
     Contents: |
       #!/usr/bin/env bash
 
@@ -64,22 +63,35 @@ Templates:
       kubectl --kubeconfig=$KUBECONFIG get nodes
 
       echo "Apply Dashboard YAML"
-      kubectl --kubeconfig=$KUBECONFIG apply -f https://raw.githubusercontent.com/kubernetes/dashboard/{{ .Param "edge-lab/dashboard-version"}}/aio/deploy/recommended.yaml
-
-      sleep 10
+      if kubectl --kubeconfig=$KUBECONFIG get namespace kubernetes-dashboard ; then
+        echo "kubernetes-dashboard namespace exists, skipping"
+      else
+        kubectl --kubeconfig=$KUBECONFIG apply -f https://raw.githubusercontent.com/kubernetes/dashboard/{{ .Param "edge-lab/dashboard-version"}}/aio/deploy/recommended.yaml
+        sleep 10
+      fi
 
       echo "Create Service Accounts"
-      kubectl --kubeconfig=$KUBECONFIG create serviceaccount dashboard-admin-sa       
-      kubectl --kubeconfig=$KUBECONFIG create clusterrolebinding dashboard-admin-sa --clusterrole=cluster-admin --serviceaccount=default:dashboard-admin-sa
+      kubectl --kubeconfig=$KUBECONFIG create serviceaccount dashboard-admin-sa || true
+      kubectl --kubeconfig=$KUBECONFIG create clusterrolebinding dashboard-admin-sa --clusterrole=cluster-admin --serviceaccount=default:dashboard-admin-sa || true
 
       echo "Create Admin User"
-      kubectl --kubeconfig=$KUBECONFIG apply -f dashboard-adminuser.yaml
-      kubectl --kubeconfig=$KUBECONFIG apply -f cluster-binding.yaml
+      if [[ -f dashboard-adminuser.yaml ]] ; then
+        kubectl --kubeconfig=$KUBECONFIG apply -f dashboard-adminuser.yaml || true
+        kubectl --kubeconfig=$KUBECONFIG apply -f cluster-binding.yaml || true
+      else
+        echo "missing key files"
+        exit 1
+      fi
 
       echo "Save Dashboard Token"
+      userid=$(kubectl --kubeconfig=$KUBECONFIG get secret -n kubernetes-dashboard --output=json | jq -r '.items[] | select(.metadata.name|startswith("admin-user")) | .metadata.name')
       tokenraw=$(kubectl --kubeconfig=$KUBECONFIG get secret -n kubernetes-dashboard --output=json | jq -r '.items[] | select(.metadata.name|startswith("admin-user")) | .data.token')
       token=$(echo $tokenraw | base64 --decode)
+      {{ if .ParamExists "edge-lab/dashboard-token" }}
+      drpcli -T $PROFILE_TOKEN profiles set $CLUSTER_PROFILE param "edge-lab/dashboard-token" to "$token"
+      {{ else }}
       drpcli -T $PROFILE_TOKEN profiles add $CLUSTER_PROFILE param "edge-lab/dashboard-token" to "$token"
+      {{ end }}
 
       echo "Save Dashboard Status"
       kubectl --kubeconfig=$KUBECONFIG describe pods -n=kubernetes-dashboard
@@ -89,7 +101,6 @@ Templates:
       {{ end }}
       echo "Done"
       exit 0
-
 Meta:
   icon: "tv"
   color: "yellow"
