enhance(vmware-lib) Switch govc context to mini-deb, govc-lib enhancements

diff --git a/vmware-lib/content/templates/govc-lib.sh.tmpl b/vmware-lib/content/templates/govc-lib.sh.tmpl
--- a/vmware-lib/content/templates/govc-lib.sh.tmpl
+++ b/vmware-lib/content/templates/govc-lib.sh.tmpl
@@ -43,3 +43,57 @@ get_member_name() {
   esac
   echo ${_member}
 }
+
+###
+#  Run the govc command with options.
+#
+#  example usage:  run_govc [quiet] cmd
+#
+#  If "quiet" is specified as ARGv1, then the Arguments will be shifted
+#  by one, will be appended to the "govc" command and no helpful
+#  "CMD: govc cmd ..." output will be printed.  The "govc" command output
+#  will not be surpressed.  If true "quiet" mode is required, then the
+#  calling application should redirect STDOUT and STDERR appropriately.
+#
+#    eg:  run_govc about > /dev/null
+#
+#  If the Param 'govc/debug' is set to 'true', then the GoVC command will
+#  simply be printed on STDOUT and not actually executed.
+###
+run_govc() {
+  local _output=1
+  local _dbg='{{.Param "govc/debug"}}'
+  local _msg
+
+  if [[ "$1" =~ .*quiet ]]
+  then
+    shift 1
+    local _output=0
+  fi
+
+  local _args="$*"
+
+  [[ "$_dbg" == "true" ]] && _msg="(DBG) " || _msg=""
+  (( $_output )) && echo "${_msg}CMD: govc $_args" || true
+  [[ "$_dbg" == "false" ]] && eval govc $_args || true
+  return $?
+}
+
+###
+#  Try really really hard to find a 'jq' binary to use.
+###
+_JQ=""
+_JQ=$(which jq)
+[[ -z "$_JQ" ]] && _JQ=$(which drpjq)    || true
+[[ -z "$_JQ" ]] && _JQ=$(which drpclijq) || true
+[[ -z "$_JQ" ]] && _JQ=$(which gojq)     || true
+if [[ -z "$_JQ" ]]; then
+  D="$(which drpcli)"
+  if [[ -n "$D" ]]; then
+    ln -s $D /usr/local/bin/drpjq
+    _JQ="/usr/local/bin/drpjq"
+  else
+    echo "FATAL: Unable to find 'jq' or alternative tool to use."
+    exit 1
+  fi
+fi
