Cleanups, datastore rework, enhance datastore

diff --git a/vmware-lib/content/tasks/govc-datastore-manage.yaml b/vmware-lib/content/tasks/govc-datastore-manage.yaml
--- a/vmware-lib/content/tasks/govc-datastore-manage.yaml
+++ b/vmware-lib/content/tasks/govc-datastore-manage.yaml
@@ -1,22 +1,25 @@
 ---
-Name: "govc-datastore-create"
-Description: "A task to create a datastore(s) on a remote ESXi instance."
+Name: "govc-datastore-manage"
+Description: "A task to manage (add/remove/list) datastore(s) on a remote ESXi instance."
 Documentation: |
-  Creates a datastore on a remote ESXi instance.
+  Add, remove, or list datastore(s) on a remote ESXi instance specified in the
+  ``esxi/datastore-mappings`` Param.
 
 RequiredParams:
   - "esxi/datastore-mappings"
   - "esxi/datastore-memberships"
+  - "esxi/datastore-command"
   - "govc/url"
   - "govc/username"
   - "govc/password"
 OptionalParams:
+  - "esxi/datastore-skip-manage"
   - "govc/datastore-create-disk"
   - "govc/datastore-create-name"
   - "govc/insecure"
   - "govc/port"
 Templates:
-  - Name: "govc-datastore-create.sh"
+  - Name: "govc-datastore-manage.sh"
     Contents: |
       #!/usr/bin/env bash
       # Create a Datastore on a remote vCenter or ESXi host with 'govc'
@@ -24,8 +27,8 @@ Templates:
 
       set -e
 
-      {{ if .Param "govc/datastore-skip-create" -}}
-      echo "Skipping datastore creation as 'govc/datastore-skip-create' is 'true'."
+      {{ if .Param "esxi/datastore-skip-manage" -}}
+      echo "Skipping datastore creation as 'esxi/datastore-skip-manage' is 'true'."
       exit 0
       {{ end -}}
 
@@ -57,6 +60,8 @@ Templates:
       # set the govc arguments based on Param values
       ARGS=""
 
+      DS_CMD='{{ .Param "esxi/datastore-command" }}'
+
       ### MORE verifiers are needed (nfs, cifs, local, etc)
 
       ###
@@ -65,11 +70,25 @@ Templates:
       #  return 0 on success
       #  return 1 on no such device
       ###
-      verify_vmfs_disk() {
+      verify_vmfs() {
         local _check="$1"
         local _devs
         _devs=$(govc host.esxcli --json storage core path list | jq -r ".Values | .[] | .Device[]")
         grep -q "$_check" <<< $_devs && return 0 || return 1
+      }
+
+      ###
+      #  TODO: is CIFS server available? is requested share available?
+      ###
+      verify_cifs() {
+        true
+      }
+
+      ###
+      #  TODO: is local path valid?  what else?
+      ###
+      verify_local() {
+        true
       }
 
       get_first_available() {
@@ -95,7 +114,7 @@ Templates:
         fi
 
         check_first_available_has_run_already
-        verify_vmfs_disk $DISK
+        verify_vmfs $DISK
         ARGS="-type vmfs -name \"$DS_NAME\" -disk=$DISK $HOST"
       }
 
@@ -132,28 +151,60 @@ Templates:
         FIRST="yes"
       }
 
+      # verify NFS mount Datastore is not already connected - GOVC barfs
+      # badly if it is
+      # ARGv 1 - Type of datastore to check for ("nfs" or "nfs41")
+      # ARgv 2 - Datastore name to check
+      # Exits with error code 1 if DS connected already
+      verify_nfs() {
+        local _type="$1"
+        local _ds="$2"
+        if govc host.esxcli storage $_type list | grep "^$_ds "
+        then
+          echo ">>> Datastore named '$_ds' connected to host."
+          case $DS_CMD in
+            add)
+              echo ">>> Exiting with error - future handling might allow this to continue as non-error?"
+              exit 1
+            ;;
+          esac
+        else
+          echo ">>> Datastore named '$_ds' does not appear to be connected."
+          case $DS_CMD in
+            remove)
+              echo ">>> Remove operation requested for '$DS_NAME', however, it is not connected."
+              echo "    No remove operation attempted."
+              exit 0
+            ;;
+          esac
+        fi
+      }
+
       # legacy values for datastore create; prior to suppoort of esxi/datastore-mappings
       SELECT='{{ .Param "govc/datastore-create-disk" }}'
       DS_NAME='{{ .Param "govc/datastore-create-name" }}'
 
       case $SELECT in
         disk=*)
-        DISK="$(echo $SELECT | sed 's/^disk=//g')"
-        if govc host.esxcli --json storage core path list | jq -r ".Values | .[] | select(.Device .[] = \"$DISK\" | .[] "
-        then
-          echo "Found device '$DISK' to create datastore on."
-        else
-          echo "FATAL Unable to find requested device '$DISK'"
-          echo "Device dump for debugging purposes..."
-          govc host.esxcli storage core path list
-          exit 1
-        fi
-        ARGS="-type vmfs -name \"$DS_NAME\" -disk=$DISK $HOST"
+          DISK="$(echo $SELECT | sed 's/^disk=//g')"
+          if govc host.esxcli --json storage core path list | jq -r ".Values | .[] | select(.Device .[] = \"$DISK\" | .[] "
+          then
+            echo "Found device '$DISK' to create datastore on."
+          else
+            echo "FATAL Unable to find requested device '$DISK'"
+            echo "Device dump for debugging purposes..."
+            govc host.esxcli storage core path list
+            exit 1
+          fi
+          ARGS_ADD="datastore.create -type vmfs -name \"$DS_NAME\" -disk=$DISK $HOST"
+          ARGS_LIST="datastore.info \"$DS_NAME\""
+          ARGS_RM="datastore.remove -ds \"$DS_NAME\" $HOST"
         ;;
         datastore_mappings)
 
         {{ if .Param "esxi/datastore-mappings" -}}
           {{ range $dsref, $dsval := ( .ComposeParam "esxi/datastore-mappings" ) -}}
+          reset_global_vars
           REF='{{ $dsref }}'
           DS_NAME='{{ get $dsval "name" }}'
           DS_TYPE='{{ get $dsval "type" }}'
@@ -175,7 +226,11 @@ Templates:
           [[ "$DS_FORCE" == "true" ]] && F="-force true" || F=""
           [[ "$DS_MODE" == "readOnly" || "$DS_MODE" == "readWrite" ]] && M="-mode $DS_MODE" || M=""
 
-          echo ">>> Beginning create for reference '$REF' datastore."
+          echo ">>> Beginning datastore manage operation '$DS_CMD' for mapping reference '$REF' datastore."
+
+          # these appear to work the same for Remove/Info
+          ARGS_LIST="datastore.info \"$DS_NAME\""
+          ARGS_RM="datastore.remove -ds \"$DS_NAME\" $DS_HOST"
 
           case $DS_TYPE in
             first_available)
@@ -185,31 +240,36 @@ Templates:
             nfs*)
               verify_data "remote-host" "$DS_RHOST"
               verify_data "remote-path" "$DS_RPATH"
-              ARGS="-type $DS_TYPE -name \"$DS_NAME\" -remote-host \"$DS_RHOST\" -remote-path \"$DS_RPATH\" $M $F $DS_HOST"
+              verify_nfs "$DS_TYPE" "$DS_NAME"
+              # datastore.create doesn't seem to work
+              #ARGS_ADD="datastore.create -type $DS_TYPE -name \"$DS_NAME\" -remote-host \"$DS_RHOST\" -remote-path \"$DS_RPATH\" $M $F $DS_HOST"
+              ARGS_ADD="host.esxcli storage $DS_TYPE add -H $DS_RHOST -readonly false -share $DS_RPATH -volume-name $DS_NAME"
+              ARGS_RM="host.esxcli storage $DS_TYPE remove -volume-name $DS_NAME"
             ;;
             cifs)
               verify_data "remote-host" "$DS_RHOST"
               verify_data "remote-path" "$DS_RPATH"
               verify_data "username" "$DS_USER"
               verify_data "password" "$DS_PASS"
+              verify_cifs
               [[ "$DS_USER" != "<no value>" ]] && U="-username $DS_USER" || U=""
               [[ "$DS_PASS" != "<no value>" ]] && P="-password $DS_PASS" || P=""
-              ARGS="-type $DS_TYPE -name \"$DS_NAME\" -remote-host \"$DS_RHOST\" -remote-path \"$DS_RPATH\" $U $P $M $F $DS_HOST"
+              ARGS_ADD="datastore.create -type $DS_TYPE -name \"$DS_NAME\" -remote-host \"$DS_RHOST\" -remote-path \"$DS_RPATH\" $U $P $M $F $DS_HOST"
             ;;
             vmfs)
               [[ "$DS_VER" != "<no value>" ]] && V="-version $DS_VER" || V=""
-              ARGS="-type $DS_TYPE -name \"$DS_NAME\" -disk \"$DS_DISK\" $M $V $F $DS_HOST"
+              verify_vmfs "$DS_DISK"
+              ARGS_ADD="datastore.create -type $DS_TYPE -name \"$DS_NAME\" -disk \"$DS_DISK\" $M $V $F $DS_HOST"
             ;;
             local)
               verify_data "path" "$DS_PATH"
-              ARGS="-type $DS_TYPE -name \"$DS_NAME\" -path \"$DS_PATH\" $M $F $DS_HOST"
+              verify_local "$DS_PATH"
+              ARGS_ADD="datastore.create -type $DS_TYPE -name \"$DS_NAME\" -path \"$DS_PATH\" $M $F $DS_HOST"
             ;;
             *)
               xiterr 1 "Datastore type '$DS_TYPE' not supported."
             ;;
           esac
-
-          reset_global_vars
           {{ end -}}
         {{ else -}}
           echo "Param 'esxi/datasotre-mappings' had no value.  Falling back to get first available disk."
@@ -218,7 +278,7 @@ Templates:
 
         ;;
         first_available)
-          echo "No 'esxi/datastore-mappings found ... falling back to default get first availalbe behavior."
+          echo "No 'esxi/datastore-mappings found.  Falling back to default get first availalbe behavior."
           get_first_available
         ;;
         *)
@@ -227,10 +287,24 @@ Templates:
       esac
 
       echo ""
-      echo "==== RUN 'govc $CMD' ===="
+      echo "==== RUN govc operation '$DS_CMD' ===="
       echo ""
 
-      run_govc datastore.create $ARGS
+      case $DS_CMD in
+        add)    run_govc $ARGS_ADD
+                echo ">>> Datastore(s) now connected:"
+                echo "=============================================================================================="
+                run_govc quiet datastore.info
+        ;;
+        remove) run_govc $ARGS_RM
+                sleep 3
+                echo ">>> Datastore(s) that remain connected:"
+                echo "=============================================================================================="
+                run_govc quiet datastore.info
+        ;;
+        list)   run_govc $ARGS_LIST ;;
+        *) xiterr 1 "Unsupported Datasstore Operation ('$DS_CMD')." ;;
+      esac
 
       echo ""
       echo "==== DONE ===="
