Revert "Merge remote-tracking branch 'upstream/v4' into v4"
This reverts commit 03a39f88f734f5ab95ebf3235ebe30f912f228fc, reversing
changes made to 89b9774e923fdc10e281764c509674b642c778fe.

diff --git a/classify/templates/classify.sh.tmpl b/classify/templates/classify.sh.tmpl
--- a/classify/templates/classify.sh.tmpl
+++ b/classify/templates/classify.sh.tmpl
@@ -9,39 +9,9 @@ set -e
 {{template "setup.tmpl" .}}
 [[ $RS_UUID ]] && export RS_UUID="{{.Machine.UUID}}"
 
-{{ $dataParameter := "classify/classification-data" }}
-{{ $functionParameter := "classify/custom-functions" }}
-{{ $disableParameter := "classify/disable-classifier" }}
-DISABLE_CLASSIFIER="{{.Param $disableParameter}}"
-{{ if ne 1 (.Param "classify/version" | int) }}
-  {{ if .ParamExists "classify/data-parameter" }}
-    {{ $dataParameter = .Param "classify/data-parameter" }}
-  {{ else }}
-    {{ $dataParameter = "unknown-data-parameter" }}
-  {{ end }}
-
-  {{ if .ParamExists "classify/function-parameter" }}
-    {{ $functionParameter = .Param "classify/function-parameter" }}
-  {{ else }}
-    {{ $functionParameter = "unknown-function-parameter" }}
-  {{ end }}
-
-  {{ if .ParamExists "classify/disable-parameter" }}
-    {{ $disableParameter = .Param "classify/disable-parameter" }}
-    {{ if .ParamExists $disableParameter }}
-      DISABLE_CLASSIFIER="{{ .Param $disableParameter }}"
-    {{ else }}
-      DISABLE_CLASSIFIER="false"
-    {{ end }}
-  {{ end }}
-{{ end }}
-
-echo "Using data parameter: {{$dataParameter}}"
-echo "Using function parameter: {{$functionParameter}}"
-echo "Using disable parameter: {{$disableParameter}}"
-
+DISABLE_CLASSIFIER="{{.Param "classify/disable-classifier"}}"
 if [[ "$DISABLE_CLASSIFIER" == "true" ]]; then
-  echo "Classification system disabled ('{{$disableParameter}}' set to 'true')."
+  echo "Classification system disabled ('classify/disable-classifier' set to 'true')."
   exit 0
 fi
 
@@ -49,20 +19,116 @@ fi
 MY_MAC_ADDR=""
 
 ###
-### Actions functions have no return
+#   Sets a given parameter to a given value on a Machine object.
 ###
-{{ template "classify-base-actions.sh.tmpl" . }}
+function set_parameter() {
+  local _parameter="$1"
+  local _value="$2"
+
+  drpcli machines set $RS_UUID param "$_parameter" to "$_value"
+}
 
 ###
-###  Test functions echo pass for success and fail for failure
+#  Adds a given ARGv1 profile to the Machine object
 ###
-{{ template "classify-base-tests.sh.tmpl" . }}
+function add_profile() {
+  local _profile="$1"
+
+  if drpcli profiles exists "$_profile"
+  then
+    if drpcli machines show $RS_UUID | jq -r '.Profiles' | grep -q "\"$_profile\""
+    then
+      echo "Profile ('$_profile') already exists on Machine - no action taken."
+    else
+      drpcli machines addprofile $RS_UUID "$_profile"
+    fi
+  else
+    echo "Requested profile ('$_profile') does not exist."
+    exit 1
+  fi
+}
+
+###
+#  Changes the Machine workflow to ARGv1 specified workflow
+###
+function change_workflow() {
+  local _wf="$1"
+
+  if drpcli workflows exists "$_wf"
+  then
+    drpcli machines update $RS_UUID "{ \"Workflow\": \"$_wf\" }"
+  else
+    echo "Requested workflow ('$_wf') does not exist."
+    exit 1
+  fi
+}
+
+###
+###  Test functions echo 0 for success and 1 for failure
+###
+
+###
+#  Generally a fallthrough function, that will always succeed if Requested###
+function always() {
+  echo "pass"
+}
+
+###
+#  Determine if the Machine is in a given in_subnet
+###
+function in_subnet() {
+  local _cidr="$1"
+  local _prefix=${_cidr#*/}
+  local _myaddr="{{.Machine.Address}}/$_prefix"
+
+  local _mynet=$(ipcalc -n $_myaddr)
+  local _thenet=$(ipcalc -n $_cidr)
+
+  if [[ "$_mynet" == "$_thenet" ]] ; then
+      echo "pass"
+  else
+      echo "fail"
+  fi
+}
+
+###
+#  Determine if the Machine has the given MAC address
+###
+function has_mac() {
+  # normalize the input MAC for comparison
+  local _mac_match=$(echo "$1" | tr -d " :-" | tr '[:upper:]' '[:lower:]')
+  get_my_mac    # sets global var MY_MAC_ADDR
+  # strip it down to 12 chars (tosses 01 type if exists)
+  _mac_match=${_mac_match:(-12)}
+
+  if [[ "$_mac_match" == "$MY_MAC_ADDR" ]]; then
+    echo "pass"
+  else
+    echo "fail"
+  fi
+}
+
+###
+#  get the Machines boot interface Mac Addr
+#  NOTE: we shouuld NOT echo anything out here
+###
+function get_my_mac() {
+  bootif_re='BOOTIF=([^ ]+)'
+  local _macaddr="UNKNOWN"
+  if [[ $(cat /proc/cmdline) =~ $bootif_re ]]; then
+    _macaddr="${BASH_REMATCH[1]//-/:}"
+    _macaddr=$(echo $_macaddr | tr -d " :-" | tr '[:upper:]' '[:lower:]')
+    _macaddr=${_macaddr:(-12)}
+  else
+    xiterr 1 "Unable to 'cat /proc/cmdline' and rematch successfully"
+  fi
+  MY_MAC_ADDR="$_macaddr"
+}
 
 # if any custom classify functions are specified, inject them here
 {{ template "classify-custom-functions.tmpl" .}}
 
-{{ if .ParamExists $dataParameter }}
-{{range $index, $group := .Param $dataParameter }}
+{{range $index, $group := .Param "classify/classification-data"}}
 
 [[ $RS_DEBUG_ENABLE ]] && echo ">>>   INDEX:  {{$index}}"
 [[ $RS_DEBUG_ENABLE ]] && echo ">>>   GROUP:  {{$group}}"
@@ -85,7 +151,6 @@ if [[ $RESULT == "pass" ]] ; then
    exit 0
  {{ end -}}
 fi
-{{end}}
 
 {{else}}
 echo "No data to classify.  Continuing without classification ..."
diff --git a/content/templates/discovery-common-bootstrap.sh.tmpl b/content/templates/discovery-common-bootstrap.sh.tmpl
--- a/content/templates/discovery-common-bootstrap.sh.tmpl
+++ b/content/templates/discovery-common-bootstrap.sh.tmpl
@@ -7,10 +7,7 @@
 macs=()
 for nic in /sys/class/net/*; do
     [[ -f $nic/type && -f $nic/address && $(cat "$nic/type") == 1 ]] || continue
-    newmac=$(cat "$nic/address")
-    # Calico is bad and makes fake addresses
-    [[ "$newmac" != "ee:ee:ee:ee:ee:ee" ]] || continue
-    macs+=($newmac)
+    macs+=($(cat "$nic/address"))
 done
 hwaddrs="$(printf '"%s",' "${macs[@]}")"
 hwaddrs="[${hwaddrs%,}]"
@@ -34,8 +31,8 @@ for tool in drpcli jq; do
     which "$tool" &>/dev/null && continue
     echo "Installing $tool in /usr/local/bin"
     case $tool in
-        drpcli) curl -kgsfLo "/usr/local/bin/$tool" "{{.ApiURL}}/files/drpcli.$ARCH.linux";;
-        jq)     curl -kgsfLo "/usr/local/bin/$tool" "{{.ApiURL}}/files/jq";;
+        drpcli) curl -gsfLo "/usr/local/bin/$tool" "{{.ProvisionerURL}}/files/drpcli.$ARCH.linux";;
+        jq)     curl -gsfLo "/usr/local/bin/$tool" "{{.ProvisionerURL}}/files/jq";;
     esac
     chmod 755 "/usr/local/bin/$tool"
 done
@@ -49,26 +46,20 @@ switch_to_control() {
     echo "${RS_UUID}" > /etc/rs-uuid
     {{template "profile.tmpl" .}}
 
-    echo "Downlading $RS_ENDPOINT/machines/$RS_UUID/control.sh"
-    if ! curl -kgsfLo /tmp/control.sh "$RS_ENDPOINT/machines/$RS_UUID/control.sh" && \
+    echo "$PROVISIONER_WEB/machines/$RS_UUID/control.sh"
+    if ! curl -g -s -f -L -o /tmp/control.sh "$PROVISIONER_WEB/machines/$RS_UUID/control.sh" && \
             grep -q '^exit 0$' /tmp/control.sh && \
             head -1 /tmp/control.sh | grep -q '^#!/bin/bash'; then
-        echo "WARNING: could not attach using HTTPS, falling back to HTTP"
-        echo "Failling back to $PROVISIONER_WEB/machines/$RS_UUID/control.sh"
-        if ! curl -kgsfLo /tmp/control.sh "$PROVISIONER_WEB/machines/$RS_UUID/control.sh" && \
-                grep -q '^exit 0$' /tmp/control.sh && \
-                head -1 /tmp/control.sh | grep -q '^#!/bin/bash'; then
-            echo "Could not load our control.sh!"
-            echo "Either the machine is not in the proper bootenv, or"
-            echo "the bootenv is broken and fell through to Sledgehammer"
-            exit 1
-        fi
+        echo "Could not load our control.sh!"
+        echo "Either the machine is not in the proper bootenv, or"
+        echo "the bootenv is broken and fell through to Sledgehammer"
+        exit 1
     fi
     chmod 755 /tmp/control.sh
     export RS_UUID BOOTDEV PROVISIONER_WEB MAC DOMAIN DNS_SERVERS HOSTNAME IP
     echo "transfer from start-up to control script"
     [[ -x /tmp/control.sh ]] && exec /tmp/control.sh
-    echo "Did not get control.sh from $RS_ENDPOINT/machines/$RS_UUID/control.sh"
+    echo "Did not get control.sh from $PROVISIONER_WEB/machines/$RS_UUID/control.sh"
     exit 1
 }
 
diff --git a/edge-lab/tasks/edge-lab-reboot-workflow.yaml b/edge-lab/tasks/edge-lab-reboot-workflow.yaml
--- a/edge-lab/tasks/edge-lab-reboot-workflow.yaml
+++ b/edge-lab/tasks/edge-lab-reboot-workflow.yaml
@@ -13,25 +13,16 @@ Templates:
 
       {{ template "setup.tmpl" . }}
 
+      {{ if .ParamExists "edge-lab/reboot-workflow" }}
+      drpcli machines meta set $RS_UUID key icon to "recycle"
+      drpcli machines meta set $RS_UUID key color to "red"
       drpcli machines workflow $RS_UUID "" >/dev/null
-      drpcli machines workflow $RS_UUID {{ .Param "edge-lab/reset-workflow" }} >/dev/null
+      drpcli machines workflow $RS_UUID {{ .Param "edge-lab/reboot-workflow" }} >/dev/null
+      {{ else }}
+      echo "Missing parameter edge-lib/reboot-workflow"
+      exit 1
+      {{ end }}
 
-      # this is going to look like a reboot, fake a powercycle
-      # MUST BE AFTER other machine updates or it will be over-written by next event
-      if drpcli events post '{
-        "Action": "powercycle",
-        "Key": "{{ .Machine.Uuid }}",
-        "Object": {{ .Machine | toJson }},
-        "Principal": "runner:{{ .Machine.Uuid }}",
-        "Type": "machines"
-      }' > /dev/null; then
-        echo "Sending Reboot Event (powercycle)"
-        sleep 5
-      else
-        echo "Warning: failed trying to post Reboot Event (powercycle)"
-      fi
-
-      echo "reboot exit code..."
       exit 192
 Meta:
   icon: "recycle"
diff --git a/flash/tasks/lenovo-firmware-flash.yml b/flash/tasks/lenovo-firmware-flash.yml
--- a/flash/tasks/lenovo-firmware-flash.yml
+++ b/flash/tasks/lenovo-firmware-flash.yml
@@ -10,7 +10,6 @@ Templates:
     Contents: |
       #!/usr/bin/env bash
       [[ {{.Param "skip-flash"}} = true ]] && exit 0
-      {{ template "set-proxy-servers.sh.tmpl" .}}
       mt="$(drpcli gohai |jq -r '.DMI.Chassis| .[0]| .SKUNumber')"
       mt="${mt:0:4}"
       /opt/OneCli/OneCli update acquire --ostype platform --scope latest --mt "$mt"
@@ -19,26 +18,17 @@ Templates:
       #!/usr/bin/env bash
       [[ {{.Param "skip-flash"}} = true ]] && exit 0
       [[ -d /sys/module/sg ]] || modprobe sg
-      {{ template "set-proxy-servers.sh.tmpl" .}}
       /opt/OneCli/OneCli update flash --noreboot
       reboot=false
       fail=false
       while read line; do
-        case $line in
-          *STATUS*)
-            echo "STATUS line is $line"
-            [[ $line = *'Package installed successfully'* ]] || [[ $line = *'Parse Firmware Package XML successfully'* ]] || lfailed=yes;;
-          *REBOOT*)
-            echo "REBOOT line is $line"
-            [[ $lfailed = no && $line = *'Reboot Required'* ]] && this_one_reboot=yes
-            [[ $lfailed = no && $line = *'reboot required'* ]] && this_one_reboot=yes
-            [[ $lfailed = no && $line = *'Reboot is Required'* ]] && this_one_reboot=yes
-            [[ $lfailed = no && $line = *'reboot is required'* ]] && this_one_reboot=yes
-            [[ $lfailed = no && $line = *'No Reboot Required'* ]] && this_one_reboot=no
-            [[ $lfailed = no && $line = *'No reboot required'* ]] && this_one_reboot=no
-            [[ $lfailed = no && $line = *'no reboot required'* ]] && this_one_reboot=no;;
-        esac
-        [[ $reboot = true || $fail = true ]] && break
+          case $line in
+             *STATUS*)
+                 [[ $line = *'Package installed successfully'* ]] || fail=true;;
+             *REBOOT*)
+                 [[ $fail = false && $line = *'Reboot Required to take effect'* ]] && reboot=true;;
+          esac
+          [[ $reboot = true || $fail = true ]] && break
       done < <(awk '/<(REBOOT|STATUS)>/' logs/*/Onecli-update_flash_status.xml |tac)
       [[ $reboot = true ]] && exit 192
       [[ $fail = false ]]
diff --git a/kube-lib/tasks/kube-lib-helm-install.yaml b/kube-lib/tasks/kube-lib-helm-install.yaml
--- a/kube-lib/tasks/kube-lib-helm-install.yaml
+++ b/kube-lib/tasks/kube-lib-helm-install.yaml
@@ -6,18 +6,28 @@ Documentation: |
   This uses the Digital Rebar Cluster pattern so cluster/profile and cluster/leader must be set.
 RequiredParams:
   - cluster/profile
-  - cluster/manager
+  - cluster/leaders
   - kube-lib/helm-version
+  - kube-lib/helm-download-url
   - kube-lib/kube-config
 ExtraClaims:
   - scope: "files"
-    action: "*"
-    specific: "*"
+    action: "get"
+    specific: "/kubernetes/helm-*"
+  - scope: "files"
+    action: "get"
+    specific: "/kubernetes/helm-amd64"
+  - scope: "files"
+    action: "post"
+    specific: "/kubernetes/helm-arm64"
+  - scope: "files"
+    action: "post"
+    specific: "/kubernetes/helm-amd64"
 Templates:
   - Name: "kube.config"
     Path: "kube.config"
     Contents: |
-      {{ .Param "kube-lib/kube-config" | toPrettyJson }}
+      {{ .ParamAsJSON "kube-lib/kube-config" }}
   - Name: "helm-install.sh"
     Path: ""
     Contents: |
@@ -25,30 +35,68 @@ Templates:
 
       {{ template "setup.tmpl" . }}
 
+      {{ template "cluster-shared.tmpl" .}}
       {{ template "download-tools.tmpl" .}}
+      export KUBECONFIG="./kube.config"
 
-      {{ if .Param "cluster/manager" }}
-        echo "Verified: Must be Cluster Manager"
-      {{ else }}
-        echo "Cluster Manager only.  Stopping execution"
+      if ! $CLUSTER_I_AM_LEADER ; then
+        echo "Leaders only.  Stopping execution"
         exit 0
-      {{ end }}
+      fi
 
-      echo "Checking Helm Install and Version"
-      if helm version ; then
-        echo "  found helm, moving on..."
+      echo "Running helm on the leader (skip for workers)..."
+
+      if which helm 2>/dev/null >/dev/null ; then
+        echo "found $(which helm) binary version $(helm version), moving on..."
       else
-        {{ $cachesource := "kube-lib/helm-version" }}
-        OS="linux"
-        ARCH="{{ .Machine.Arch }}"
+        HELM_VERSION="{{ .Param "kube-lib/helm-version"}}"
         BINARIES="/usr/local/bin/helm"
-        {{ $arch := list "linux" .Machine.Arch | join "-" }}
-        {{ $file := .Param $cachesource }}
-        {{ $source := get $file $arch }}
-        drp_cache "{{ get $file "name" }}" "{{ get $file "version" }}" "$OS" "$ARCH" "{{ get $source "url" }}" "{{ get $source "sha256sum" }}" "{{ get $source "explode" }}"
-        chmod +x "{{ get $file "name" }}"
-        mv "{{ get $file "name" }}" $BINARIES
+        if drpcli files exists "kubernetes/helm-$arch" 2>/dev/null >/dev/null ; then
+          echo "Found in DRP kubernetes/helm-$arch - downloading from there"
+          drpcli files download "kubernetes/helm-$arch" to $BINARIES
+        else
+          if [[ "$HELM_VERSION" == "latest" ]]; then
+            echo "Looking up latest version, requested $HELM_VERSION"
+            download -L --remote-name-all "https://api.github.com/repos/helm/helm/releases/latest" -o helm_latest.json
+            HELM_VERSION="$(jq -r .tag_name <<< cat helm_latest.json)"
+          fi
+          echo "Using Helm Version $HELM_VERSION"
+          echo "Installing Helm for arch $arch from {{ .Param "kube-lib/helm-download-url" }}"
+          HELM_DOWNLOAD="{{ .Param "kube-lib/helm-download-url" -}}/helm-$HELM_VERSION-linux-$arch.tar.gz"
+          echo "Download helm from $HELM_DOWNLOAD"
+          download -L --remote-name-all "$HELM_DOWNLOAD" -o helm.tar.gz
+          echo "Download helm checksum from $HELM_DOWNLOAD.sha256"
+          download -L --remote-name-all "$HELM_DOWNLOAD.sha256" -o helm.tar.gz.sha256
 
+          if [[ "$(sha256sum helm.tar.gz)" == "$(cat helm.tar.gz.sha256)  helm.tar.gz" ]]; then
+            echo "Checksum Test Pass: $(cat helm.tar.gz.sha256)"
+          else
+            echo "Checksum Does not match: $(cat helm.tar.gz.sha256)"
+            sha256sum helm.tar.gz
+            exit 1
+          fi
+          if tar --version 2>/dev/null >/dev/null ; then
+            echo "tar installed, no action"
+          else
+            case $osfamily in
+              redhat|centos) sudo yum install -y tar ;;
+              debian|ubuntu) sudo apt install -y tar ;;
+              *) >&2 echo "Unsupported package manager family '$osfamily'."
+                 exit 1 ;;
+            esac
+          fi
+          tar -zxvf helm.tar.gz
+          if [[ -e linux-$arch/helm ]] ; then
+            echo "save downloaded files to kubernetes/helm-$arch for next pass"
+            drpcli files upload linux-$arch/helm as kubernetes/helm-$arch
+            echo "moving from linux-$arch/helm to $BINARIES"
+            mv linux-$arch/helm $BINARIES
+          else
+            echo "ERROR: did not create linux-$arch/helm!"
+            exit 1
+          fi
+        fi
+        chmod +x $BINARIES
         echo "helm downloaded to $BINARIES"
       fi
 
diff --git a/kube-lib/tasks/kube-lib-kubectl-install.yaml b/kube-lib/tasks/kube-lib-kubectl-install.yaml
--- a/kube-lib/tasks/kube-lib-kubectl-install.yaml
+++ b/kube-lib/tasks/kube-lib-kubectl-install.yaml
@@ -1,6 +1,6 @@
 ---
-Name: "kube-lib-kubectl-install"
 Description: "Install KubeCTL"
+Name: "kube-lib-kubectl-install"
 Documentation: |
   Installs KubeCTL on machine.
 
@@ -11,23 +11,68 @@ Documentation: |
   Air-Gap: populate files/kubernetes/kubectl-[arch] to avoid download.
 RequiredParams:
   - kube-lib/kubernetes-version
+  - kube-lib/kubernetes-download-url
   - kube-lib/kube-config
 ExtraClaims:
   - scope: "files"
-    action: "*"
-    specific: "*"
+    action: "get"
+    specific: "/kubernetes/kubectl-amd64"
+  - scope: "files"
+    action: "get"
+    specific: "/kubernetes/kubectl-arm64"
+  - scope: "files"
+    action: "post"
+    specific: "/kubernetes/kubectl-amd64"
+  - scope: "files"
+    action: "post"
+    specific: "/kubernetes/kubectl-arm64"
 Templates:
   - Name: "kube.config"
     Path: "kube.config"
     Contents: |
-      {{ .Param "kube-lib/kube-config" | toPrettyJson }}
+      {{ .ParamAsJSON "kube-lib/kube-config" }}
   - Name: "kubectl-install.sh"
     Path: ""
     Contents: |
       #!/usr/bin/env bash
 
       {{ template "setup.tmpl" . }}
-      {{ template "kube-lib-kubectl-install.tmpl" .}}
+      {{ template "download-tools.tmpl" .}}
+      export KUBECONFIG="./kube.config"
+
+      if which kubectl 2>/dev/null >/dev/null ; then
+        echo "found $(which kubectl) binary, moving on..."
+      else
+        BINARIES="/usr/local/bin/kubectl"
+
+        if drpcli files exists "kubernetes/kubectl-$arch" 2>/dev/null >/dev/null ; then
+          echo "Found in DRP kubernetes/kubectl-$arch - downloading from there"
+          drpcli files download "kubernetes/kubectl-$arch" to $BINARIES
+        else
+          KUBECTL_VERSION="{{ .Param "kube-lib/kubernetes-version" }}"
+          if [[ "$KUBECTL_VERSION" == "latest" ]]; then
+            echo "Looking up latest version"
+            KUBECTL_VERSION=$(download -L --remote-name-all "{{ .Param "kube-lib/kubernetes-download-url" }}/stable.txt")
+          fi
+          echo "Using kubectl Version $KUBECTL_VERSION"
+          echo "Installing kubectl for arch $arch from {{ .Param "kube-lib/kubernetes-download-url" }}"
+          DOWNLOAD="{{ .Param "kube-lib/kubernetes-download-url" -}}/$KUBECTL_VERSION/bin/linux/$arch/kubectl"
+          echo "Download kubectl from $DOWNLOAD"
+          download -L --remote-name-all "$DOWNLOAD" -o kubectl
+
+          if [[ -e kubectl ]] ; then
+            echo "save downloaded files to kubernetes/kubectl-$arch for next pass"
+            drpcli files upload kubectl as kubernetes/kubectl-$arch
+            echo "moving from kubectl to $BINARIES"
+            mv kubectl $BINARIES
+          else
+            echo "ERROR: did not download kubectl!"
+            exit 1
+          fi
+        fi
+        echo "kubectl downloaded to $BINARIES, setting +x"
+        chmod +x $BINARIES
+      fi
 
       echo "Done"
       exit 0
diff --git a/task-library/tasks/bootstrap-contexts.yaml b/task-library/tasks/bootstrap-contexts.yaml
--- a/task-library/tasks/bootstrap-contexts.yaml
+++ b/task-library/tasks/bootstrap-contexts.yaml
@@ -10,13 +10,13 @@ Documentation: |
   * Stage installs Podman and the Docker-Context Plugin even if you do not have Docker-Contexts defined
   * Contexts are a licensed feature (the stage will abort if no license is exists)
 
-  1. Installs Podman/Docker on DRP Host
+  1. Installs Podman on DRP Host
   1. Installs the Docker-Context from Catalog
   1. Creates the runner context if missing
   1. Attempts to build & upload images for all Docker-Contexts
-  1. Initializes Podman/Docker for all Contexts
+  1. Initializes Podman for all Contexts
 
-  Podman/Docker build files are discovered in the following precidence order:
+  Podman build files are discovered in the following precidence order:
   1. using Container Buildfile from files/contexts/docker-build/[contextname]
   1. using URL from Meta.Imagepull
   1. using Container  Buildfile downloaded Context Meta.Dockerfile
@@ -40,13 +40,29 @@ ExtraClaims:
     specific: "rackn-license"
 Templates:
   - Contents: |-
+      {
+        "Name": "runner",
+        "Description": "Run DRPCLI in Docker Context",
+        "Documentation": "Very minimal container to run the DRPCLI as a starting or idle point for Machines. This provides a very low overhead system to start or complete workflows so that tasks can continue to execute even if the target machine is not available (or never exists).",
+        "Engine": "docker-context",
+        "Image": "digitalrebar-context-runner",
+        "Meta": {
+          "icon": "cube",
+          "color": "green",
+          "copyright": "RackN 2020",
+          "Dockerpull": "digitalrebar/context-runner"
+        }
+      }
+    Name: "runner-context"
+    Path: "runner.json"
+  - Contents: |-
       #!/bin/bash
       # RackN Copyright 2020
 
       set -e
       {{template "setup.tmpl" .}}
 
-      if drpcli contents exists rackn-license >/dev/null 2>/dev/null ; then
+      if drpcli contents exists rackn-license ; then
         echo "license installed, no action"
       else
         echo "SKIPPING due to missing RackN license"
@@ -57,52 +73,25 @@ Templates:
         echo "No Docker Contexts"
       fi
 
-      tool="podman"
-      if ! which podman || ! which docker ; then
+      if ! which podman ; then
         FAMILY=$(grep "^ID=" /etc/os-release | tr -d '"' | cut -d '=' -f 2)
-        echo "Installing Podman/Docker for $FAMILY"
+        echo "Installing Podman"
         case $FAMILY in
-          redhat|centos)
-            if which dnf > /dev/null 2>&1 ; then
-              dnf -y install podman
-            elif which yum > /dev/null 2>&1 ; then
-              yum -y install podman
-            else
-              echo "No 'yum' or 'dnf' found on $FAMILY OS.  Unable to install 'podman'."
-              exit 1
-            fi
-            ;;
+          redhat|centos) yum install -y dnf; dnf install -y podman ;;
           debian|ubuntu) . /etc/os-release
             echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
             curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
-            sudo apt-get update -qq; sudo apt-get -qq -y install podman
-            ;;
-          alpine)
-            apk add podman
-            ;;
-          amzn)
-            sudo amazon-linux-extras install -y docker
-            sudo service docker start
-            sudo usermod -a -G docker ec2-user
-            sudo systemctl enable --now docker
-            tool="docker"
-            ;;
+            sudo apt-get update -qq; sudo apt-get -qq -y install podman ;;
           *) >&2 echo "Unsupported package manager family '$FAMILY'."
-             exit 1
-            ;;
+             exit 1 ;;
         esac
-      echo
-        echo "Detected $tool version: $($tool version)"
       fi
 
-      echo "Relax SELinux - not for production!"
-      setenforce Permissive || true
-
-      echo "$tool installed successfully"
+      echo "Podman installed successfully"
 
       echo "Install Docker-Context"
-      pv="tip"
-      if drpcli plugin_providers exists docker-context >/dev/null 2>/dev/null; then
+      pv="stable"
+      if drpcli plugin_providers exists docker-context; then
         pv="$(drpcli plugin_providers show docker-context | jq .Version -r)"
         echo "Plugin Exists at version $pv"
       else
@@ -110,11 +99,12 @@ Templates:
         drpcli catalog item install docker-context --version=$pv
       fi
 
-      if drpcli contexts exists drpcli-runner >/dev/null 2>/dev/null ; then
-        echo "Built-In Runner Detected"
+      echo "Create Runner Context if missing (requires license)"
+      if drpcli contexts exists runner ; then
+        echo "  runner context exists, no action"
       else
-        echo "ERROR: this process requires the built-in runner context"
-        exit 1
+        echo "  runner context missing, creating"
+        drpcli contexts create runner.json
       fi
 
       echo "Check which files are uploaded (error = none)"
@@ -151,21 +141,21 @@ Templates:
             if [[ "$dockerbuild" != "" ]]; then
               echo "    pulling dockerfile from contexts/docker-build/$context"
               drpcli files download contexts/docker-build/$context > $context-dockerfile
-              $tool build --tag=$image --file="$context-dockerfile" .
+              podman build --tag=$image --file="$context-dockerfile" .
             elif [[ "$dockerfile" != "null" ]]; then
               echo "    pulling docker build from $dockerfile"
               curl -fsSL $dockerfile -o $context-dockerfile
-              $tool build --tag=$image --file="$context-dockerfile" .
+              podman build --tag=$image --file="$context-dockerfile" .
             elif [[ "$dockerpull" != "null" ]]; then
               echo "    pulling container image from $dockerpull"
-              $tool pull $dockerpull
+              podman pull $dockerpull
               echo "    tagging $dockerpull as $image"
-              $tool tag $dockerpull $image
+              podman tag $dockerpull $image
             else
               echo "!! Stopping context-bootstrap - missing container image for $context"
               exit 1
             fi
-            $tool save $image > /root/$context.tar
+            podman save $image > /root/$context.tar
             gzip /root/$context.tar
             echo "  Uploading Container from /root/$context.tar.gz"
             drpcli files upload /root/$context.tar.gz as "contexts/docker-context/$image"
@@ -175,18 +165,9 @@ Templates:
           fi
         else
           echo "  Found $container_sum in files/contexts/docker-context, skipping upload"
-          if $tool images | grep -q localhost/$image ; then
-            echo   "  localhost/$image is installed, removing to ensure correct download"
-            $tool rmi localhost/$image
-          else
-            echo   "  localhost/$image does NOT exist locally, no action"
-          fi
         fi
         i=$(($i + 1))
       done
-
-      echo "Restart Plugin (handles case where plugin exists before podman"
-      drpcli plugins runaction docker-context restartProvider
 
       echo "Populate the contexts"
       i=0
