feat(edge-lab): map nfs to k3s data

diff --git a/edge-lab/templates/k3s-install.sh.tmpl b/edge-lab/templates/k3s-install.sh.tmpl
--- a/edge-lab/templates/k3s-install.sh.tmpl
+++ b/edge-lab/templates/k3s-install.sh.tmpl
@@ -31,6 +31,36 @@ case $arch in
         exit 1;;
 esac
 
+{{ if .ParamExists "edge-lab/nfs-share" }}
+FAMILY=$(grep "^ID=" /etc/os-release | tr -d '"' | cut -d '=' -f 2)
+echo "Installing NFS client for :  '$FAMILY'"
+if [[ -f /mnt/nfs/share/test.0 ]] ; then
+  echo "share already mounted, skipping"
+else
+  case $FAMILY in
+    redhat|centos) sudo yum -y install nfs-utils ;;
+    debian|ubuntu) sudo apt -y install nfs-common ;;
+    *) >&2 echo "Unsupported package manager family '$FAMILY'."
+       exit 1 ;;
+  esac
+  mkdir -p /mnt/nfs/share
+  mount {{ .Param "edge-lab/nfs-share" }} /mnt/nfs/share
+  if [[ -f /mnt/nfs/share/test.0 ]] ; then
+    echo "share mounted and verified.  create machine directory"
+    mkdir -p /mnt/nfs/share/{{ .Machine.Name }}
+    echo "attach k3s containerd to nfs containerd"
+    mkdir -p /mnt/nfs/share/{{ .Machine.Name }}/containerd
+    mkdir -p /run/k3s/containerd
+    ln -s /mnt/nfs/share/{{ .Machine.Name }}/containerd /run/k3s/containerd
+  else
+    echo "cannot find shared file { .Param "edge-lab/nfs-share" }}/test.0"
+    exit 1
+  fi
+fi
+{{ else }}
+echo "No NFS share avilable, skipping"
+{{ end }}
+
 # Fix hostname lookup
 echo "{{.Machine.Address}} $(hostname -s) $(hostname)" >> /etc/hosts
 
@@ -43,9 +73,9 @@ echo "Checking for $ARCH"
 if ! which k3s ; then
   if $CLUSTER_I_AM_LEADER; then
     drpcli machines meta set $RS_UUID key icon to download
-    if drpcli files exists "k3s/k3s"; then
+    if drpcli files exists "k3s/k3s-$arch"; then
       echo "Found in DRP files/k3s - downloading from there"
-      drpcli files download "k3s/k3s" to $BINARIES
+      drpcli files download "k3s/k3s-$arch" to $BINARIES
     else
       K3S_URL="{{ .Param "k3s/download-url" }}/download/{{ .Param "k3s/version" }}"
       echo "Download k3s from $K3S_URL/${ARCH}"
@@ -62,7 +92,7 @@ if ! which k3s ; then
       fi
 
       mv $ARCH $BINARIES
-      drpcli files upload "$BINARIES" as "k3s/k3s"
+      drpcli files upload "$BINARIES" as "k3s/k3s-$arch"
     fi
     drpcli machines meta set $RS_UUID key icon to cog
   else
@@ -70,8 +100,8 @@ if ! which k3s ; then
     drpcli machines meta set $RS_UUID key color to grey
     cluster_wait_for_variable "k3s/node-token"
     drpcli machines meta set $RS_UUID key color to yellow
-    echo "download binaries from DRP k3s/k3s"
-    drpcli files download "k3s/k3s" to $BINARIES
+    echo "download binaries from DRP k3s/k3s-$arch"
+    drpcli files download "k3s/k3s-$arch" to $BINARIES
   fi
   if [ -f $BINARIES ] ; then
     chmod +x $BINARIES
@@ -90,7 +120,7 @@ if $CLUSTER_I_AM_LEADER ; then
   echo "I am leader - run k3s server"
 
   K3S_URL=https://{{ .Machine.Address }}:{{ .Param "k3s/api-port" }}
-  EXECSTART="${BINARIES} server --bind-address={{ .Machine.Address }} --https-listen-port={{ .Param "k3s/api-port" }}"
+  EXECSTART="${BINARIES} server --bind-address={{ .Machine.Address }} --node-label=worker --https-listen-port={{ .Param "k3s/api-port" }} --node-label=worker"
   SYSTEMD_TYPE="notify"
 
   drpcli machines meta set $RS_UUID key icon to anchor
@@ -107,7 +137,7 @@ else
 
   echo "Running Agent: join with k3s/node-token value"
   K3S_URL=$(jq -r '.clusters[0].cluster.server' <<< "$ADMIN_CONFIG")
-  EXECSTART="${BINARIES} agent --server ${K3S_URL} --token ${K3S_TOKEN}"
+  EXECSTART="${BINARIES} agent --server ${K3S_URL} --node-label=worker --token ${K3S_TOKEN}"
   SYSTEMD_TYPE="exec"
   # Set machine icon and color for KRIB cluster building
   drpcli machines meta set $RS_UUID key icon to ship
@@ -161,8 +191,10 @@ fi
 
 systemctl daemon-reload && systemctl start k3s
 
-echo "create symlink for kubectl"
+echo "create symlinks for kubectl and others"
 ln -sf k3s $INSTALL_DIR/kubectl
+ln -sf k3s $INSTALL_DIR/crictl
+ln -sf k3s $INSTALL_DIR/ctr
 
 echo "waiting 3 seconds"
 sleep 3
