add join-up script for discovery that allows AWS machines to join from the unknown machine bootenv

diff --git a/content/bootenvs/discovery.yml b/content/bootenvs/discovery.yml
--- a/content/bootenvs/discovery.yml
+++ b/content/bootenvs/discovery.yml
@@ -134,6 +134,111 @@ Templates:
         initrd (tftp)/{{$.Env.PathForArch "tftp" $initrd "arm64"}}
         {{end}}
       }
+  - Name: "join-up.sh"
+    Path: "machines/join-up.sh"
+    Contents: |
+      #!/bin/bash
+      # Register Cloud Machines into Digital Rebar
+      # Copyright 2017, RackN
+      #
+      # Licensed under the Apache License, Version 2.0 (the "License");
+      # you may not use this file except in compliance with the License.
+      # You may obtain a copy of the License at
+      #
+      #  http://www.apache.org/licenses/LICENSE-2.0
+      #
+      # Unless required by applicable law or agreed to in writing, software
+      # distributed under the License is distributed on an "AS IS" BASIS,
+      # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+      # See the License for the specific language governing permissions and
+      # limitations under the License.
+      #
+
+      export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
+      PROVISIONER_WEB="{{.ProvisionerURL}}"
+
+      ARCH="$(uname -m)"
+      case $ARCH in
+          amd64|x86_64) ARCH=amd64;;
+          arm64|aarch64) ARCH=arm64;;
+          *)
+              echo "Unknown arch $ARCH"
+              exit 1;;
+      esac
+      # Perform minimal required bootstrapping for discovery
+      export RS_TOKEN="{{.GenerateToken}}"
+      export RS_ENDPOINT="{{.ApiURL}}"
+      mkdir -p /usr/local/bin
+      grep -q '/usr/local/bin' <<< "$PATH" || export PATH="$PATH:/usr/local/bin"
+      for tool in drpcli jq; do
+          which "$tool" &>/dev/null && continue
+          echo "Installing $tool in /usr/local/bin"
+          case $tool in
+              drpcli) curl -gsfLo "/usr/local/bin/$tool" "{{.ProvisionerURL}}/files/drpcli.$ARCH.linux";;
+              jq)     curl -gsfLo "/usr/local/bin/$tool" "{{.ProvisionerURL}}/files/jq";;
+          esac
+          chmod 755 "/usr/local/bin/$tool"
+      done
+      unset tool
+
+      # This only works for AWS - add other cloud types!!
+      HOSTNAME="$(curl http://169.254.169.254/latest/meta-data/public-hostname)"
+
+      # Lookup UUID
+      echo "$(drpcli machines list)"
+      JSON="$(drpcli machines list Name=\"${HOSTNAME}\")"
+
+      # See if we have already been created (array has 1 element).
+      if [[ $(jq length==1 <<< $JSON) == "true" ]]; then
+          RS_UUID="$(jq -r '.[0].Uuid' <<< "$JSON")"
+          echo "Machine $HOSTNAME exists with UUID $RS_UUID"
+      else
+          echo "Machine $HOSTNAME not found.  Adding..."
+          MYIP="$(curl http://169.254.169.254/latest/meta-data/public-ipv4)"
+          MAC="$(curl http://169.254.169.254/latest/meta-data/mac)"
+          CLOUD="aws"
+          INSTANCEID="$(curl http://169.254.169.254/latest/meta-data/instance-id)"
+          INSTANCETYPE="$(curl http://169.254.169.254/latest/meta-data/instance-type)"
+          # Create a new node for us,
+          # Add the default noderoles we will need, and
+          # Let the annealer do its thing.
+          while ! JSON="$(drpcli machines create "{\"Name\": \"$HOSTNAME\",
+                                               \"Address\": \"$MYIP\",
+                                               \"Arch\": \"$ARCH\",
+                                               \"Meta\": {\"icon\":\"cloud\"},
+                                               \"Params\": {
+                                                \"cloud/provider\":\"$CLOUD\",
+                                                \"cloud/instance-type\":\"$INSTANCETYPE\",
+                                                \"cloud/instance-id\":\"$INSTANCEID\"
+                                              },
+                                               \"HardwareAddrs\": [\"$MAC\"]}")"; do
+              echo "We could not create a node for ourself, trying again."
+              sleep 5
+          done
+          RS_UUID="$(jq -r '.Uuid' <<< "$JSON")"
+          echo "Machine $HOSTNAME added with UUID $RS_UUID"
+      fi
+      echo "${RS_UUID}" > /etc/rs-uuid
+
+      {{template "profile.tmpl" .}}
+
+      echo "$PROVISIONER_WEB/machines/$RS_UUID/control.sh"
+      if ! curl -g -s -f -L -o /tmp/control.sh "$PROVISIONER_WEB/machines/$RS_UUID/control.sh" && \
+          grep -q '^exit 0$' /tmp/control.sh && \
+          head -1 /tmp/control.sh | grep -q '^#!/bin/bash'; then
+          echo "Could not load our control.sh!"
+          exit 1
+      fi
+      chmod 755 /tmp/control.sh
+
+      export RS_UUID BOOTDEV PROVISIONER_WEB MAC DOMAIN DNS_SERVERS HOSTNAME MYIP
+
+      echo "transfer from start-up to control script"
+
+      [[ -x /tmp/control.sh ]] && exec /tmp/control.sh
+
+      echo "Did not get control.sh from $PROVISIONER_WEB/machines/$RS_UUID/control.sh"
+      exit 1
   - Name: "start-up.sh"
     Path: "machines/start-up.sh"
     Contents: |
