wip(edge-lab): add kube-lib, remove edgelab k3s
wip(edge-lab): refactor for kube-lib

fix(task-library): storage reset was in wrong place, not protected by conditional

fix(edge-lab): typo in catalog check

fix(kube-lib): fix checksum in k3s version

fix(kube-lib): add arm64 checksums

refactor(edge-lab): increase timeout

diff --git a/kube-lib/tasks/kube-lib-k3s-machine-install.yaml b/kube-lib/tasks/kube-lib-k3s-machine-install.yaml
--- a/kube-lib/tasks/kube-lib-k3s-machine-install.yaml
+++ b/kube-lib/tasks/kube-lib-k3s-machine-install.yaml
@@ -47,7 +47,12 @@ Templates:
 
       {{ if .Param "cluster/leader" }}
 
+
       echo "========== I am leader - run k3s server ========="
+      {{ if .ParamExists "kube-lib/kube-config" }}
+        echo "ERROR - you must clear 'kube-lib/kube-config' in $CLUSTER_PROFILE value before installing new k3s leader!"
+        exit 1
+      {{ end }}
       K3S_URL=https://{{ .Machine.Address }}:{{ .Param "kube-lib/api-port" }}
       EXECSTART="server --bind-address={{ .Machine.Address }} --node-label=leader --https-listen-port={{ .Param "kube-lib/api-port" }} --selinux"
       SYSTEMD_TYPE="notify"
